import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docsSidebar: [
    'intro',
    'migration/to-v7.0.0',
    {
      type: 'category',
      label: 'Socket',
      link: {
        type: 'generated-index',
        description: 'Learn about the Socket type and what we can do with it.'
      },
      items: [
        'socket/configuration',
        'socket/connecting',
        'socket/connecting-via-proxy',
        'socket/history-sync',
        'socket/receiving-updates',
        'socket/handling-messages',
        'socket/sending-messages',
        'socket/group-management',
        'socket/privacy',
        'socket/appstate-updates',
        'socket/business-features',
        'socket/broadcast-lists'
      ],
    },
    'faq'
  ],
  refSidebar: [{type: 'autogenerated', dirName: 'api'}]
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
